[package]
license = "Apache-2.0"
name = "business"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.0"
os_utils = { path = "../os_utils", default-features = false }
tracing = "0.1.29"

[target.'cfg(windows)'.dependencies]
fs_extra = "1.2.0"
