[package]
edition.workspace = true
license.workspace = true
name = "business"
version.workspace = true

[dependencies]
once_cell = "1.0"
os_utils = { path = "../os_utils", default-features = false }
tracing = "0.1.29"

[target.'cfg(windows)'.dependencies]
fs_extra = "1.2.0"
