[package]
edition.workspace = true
license.workspace = true
name = "test_runner"
version.workspace = true

[dependencies]
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
    "blocking",
] }
