const localPlugins = [
    // {
    //     "name": "centre",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "contact",
    //     "entry": "index.js",
    //     "description": "个人中心。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "个人中心",
    //     "type": "顶部工具栏",
    //     "visible": false
    // },
    // {
    //     "name": "contact",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "contact",
    //     "entry": "index.js",
    //     "description": "扫码添加客服企业微信。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "联系客服",
    //     "type": "顶部工具栏",
    //     "visible": false
    // },
    // {
    //     "name": "dataSet",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "dataSet",
    //     "entry": "index.js",
    //     "description": "用于接入、管理数据源，包括主流数据库和各云厂商的对象存储服务。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "数据集成",
    //     "type": "左侧导航栏",
    //     "visible": true
    // },
    // {
    //     "name": "datalabel",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "datalabel",
    //     "entry": "index.js",
    //     "description": "数据标注",
    //     "publisher": "https://baihai.co/",
    //     "icon": "static/icon/logo.png",
    //     "title": "数据标注",
    //     "type": "左侧导航栏",
    //     "visible": true
    // },
    // {
    //     "name": "environment",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "environment",
    //     "entry": "index.js",
    //     "description": "切换代码运行环境。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "环境切换",
    //     "type": "工作区页面底部工具&状态栏",
    //     "visible": false
    // },
    // {
    //     "name": "feedback",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "feedback",
    //     "entry": "index.js",
    //     "description": "用户反馈问题和建议。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "用户反馈",
    //     "type": "顶部工具栏",
    //     "visible": false
    // },
    // {
    //     "name": "modelwarenhouse",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "modelwarenhouse",
    //     "entry": "index.js",
    //     "description": "用于管理和共享您的模型资产",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "模型管理",
    //     "type": "左侧导航栏",
    //     "visible": true
    // },
    // {
    //     "name": "monitor",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "monitor",
    //     "entry": "index.js",
    //     "description": "用于查看当前项目正在运行的作业以及资源用量。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "作业和资源监控",
    //     "type": "左侧导航栏",
    //     "visible": true
    // },
    // {
    //     "name": "networkstatus",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "networkstatus",
    //     "entry": "index.js",
    //     "description": "当前网络连接状态。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "网络检测",
    //     "type": "工作区页面底部工具&状态栏",
    //     "visible": false
    // },
    // {
    //     "name": "notification",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "notification",
    //     "entry": "index.js",
    //     "description": "接收和管理通知消息。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "通知中心",
    //     "type": "顶部工具栏",
    //     "visible": false
    // },
    // {
    //     "name": "optuna",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "optuna",
    //     "entry": "index.js",
    //     "description": "超参数调优",
    //     "publisher": "https://baihai.co/",
    //     "icon": "static/icon/logo.png",
    //     "title": "optuna",
    //     "type": null,
    //     "visible": true
    // },
    // {
    //     "name": "teams",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "teams",
    //     "entry": "index.js",
    //     "description": "切换不同的项目",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "项目切换",
    //     "type": "顶部工具栏",
    //     "visible": false
    // },
    // {
    //     "name": "tensorboard",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "tensorboard",
    //     "entry": "index.js",
    //     "description": "TensorBoard提供了机器学习实验所需的可视化功能和工具。",
    //     "publisher": "https://baihai.co/",
    //     "icon": "static/tensorboard.png",
    //     "title": "TensorBoard",
    //     "type": "左侧导航栏",
    //     "visible": true
    // },
    // {
    //     "name": "usage",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "usage",
    //     "entry": "index.js",
    //     "description": "当前资源用量显示器。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "资源用量",
    //     "type": "工作区页面底部工具&状态栏。",
    //     "visible": false
    // },
    // {
    //     "name": "workflow",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "workflow",
    //     "entry": "index.js",
    //     "description": "工作流支持用户通过可视化拖拽方式，将数据处理、模型训练等任务串联成工作流，并可以设置定时自动执行。",
    //     "publisher": "https://baihai.co/",
    //     "icon": null,
    //     "title": "工作流",
    //     "type": "左侧导航栏",
    //     "visible": true
    // },
    // {
    //     "name": "colony",
    //     "version": "2.0.0",
    //     "optionalVersion": [],
    //     "url": "colony",
    //     "entry": "index.js",
    //     "title": "服务集群",
    //     "type": "左侧导航栏",
    //     "visible": true
    // }
]

module.exports = localPlugins